# Site settings
name: Li Research Lab
email: yul549.ucsd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Group website of the Li lab of materials research for sustainable energy applications
  at the Hong Kong University of Science and Technology (Guangzhou).
baseurl: '' # the subpath of the site, e.g. /team/
url: 'https://liresearchlab.github.io' # the base hostname & protocol for the site  # 'http://localhost:4000/'
twitter_username: YuhengLI9
github_username: liresearchlab

# Build settings
markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css

plugins:
  - jekyll-gzip
  - jekyll-twitter-plugin

gzip:
  replace_files: true

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"
  - "projects/siv-cst/beast/main/empiricalTrees/xml/*"
  - "projects/siv-cst/beast/supplement/discreteTraits/xml/*"
  - "projects/siv-cst/beast/supplement/empiricalTrees/xml/*"
  - "projects/dengue-antigenic-dynamics/titer_model/seasia_output/*"

readmes:
  - blab/chikv
  - blab/dengue-antigenic-dynamics
  - blab/flu-forecasting
  - blab/genomic-horizon
  - blab/h3n2-reassortment
  - blab/h5n1-cambodia
  - blab/mers-structure
  - blab/mumps-wa-phylodynamics
  - blab/ncov-cryptic-transmission
  - blab/ncov-phylodynamics
  - blab/ncov-wa-d614g
  - blab/ncov-wa-phylodynamics
  - blab/nextflu
  - blab/roka
  - blab/seasonal-cov-adaptive-evolution
  - blab/siv-cst
  - blab/unsampled
  - blab/yellow-fever
  - blab/zika-colombia
  - blab/zika-usvi
  - seattleflu/id3c
  - trvrb/antigen
  - trvrb/PACT
  - trvrb/stem

projects:
  - blab/global-migration
  - blab/mitii
  - blab/mumps-seq
  - blab/zika-seq
  - trvrb/ancestry
  - trvrb/coaltrace
  - trvrb/divergence
  - trvrb/dynamics-practical
  - trvrb/flutrace
  - trvrb/gs541-phylodynamics
  - trvrb/haplotypes
  - trvrb/medium-data
  - trvrb/phylodynamics-lecture
  - trvrb/sctrace
  - trvrb/sismid
