# Site settings
name: Li Research Lab
email: yul549.ucsd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Group website of the Li lab of materials research for sustainable energy applications
  at the Hong Kong University of Science and Technology (Guangzhou).
baseurl: '/liresearchlab.github.io' # the subpath of the site, e.g. /team/
url: 'https://liresearchlab.github.io' # the base hostname & protocol for the site  # 'http://localhost:4000/'
twitter_username: YuhengLI9
github_username: liresearchlab

# Build settings
markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css

#plugins:
#  - jekyll-gzip
#  - jekyll-twitter-plugin

gzip:
  replace_files: true

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"
